apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter
  labels:
    app: starter
spec:
  selector:
    matchLabels:
      app: starter
  replicas: 1
  template:
    metadata:
      labels:
        app: starter
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: starter
          image: "registry.camunda.cloud/team-zeebe/starter:release-8-5-x-47ce446"
          imagePullPolicy: IfNotPresent
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=camunda-zeebe-gateway:26500
                -Dapp.starter.rate=100
                -Dapp.starter.durationLimit=0
                -Dzeebe.client.requestTimeout=62000
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: starter-config
                optional: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"
      imagePullSecrets:
        - name: registry-camunda-cloud