apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: worker
          image: "registry.camunda.cloud/team-zeebe/worker:release-8-5-x-47ce446"
          imagePullPolicy: IfNotPresent
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=camunda-zeebe-gateway:26500
                -Dzeebe.client.requestTimeout=62000
                -Dapp.worker.capacity=60
                -Dapp.worker.pollingDelay=1ms
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: worker-config
                optional: true
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"
      imagePullSecrets:
        - name: registry-camunda-cloud