---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.97.4
      hooks:
          - id: terraform_fmt
          - id: terraform_tflint
    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
          - id: actionlint
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
          - id: shellcheck
            args: [--external-sources, --source-path, .github/workflows/scripts]
    - repo: https://github.com/renovatebot/pre-commit-hooks
      rev: 39.205.1
      hooks:
          - id: renovate-config-validator
            args: [--strict]


    - repo: https://github.com/adrienverge/yamllint
      rev: v1.37.1
      hooks:
          - id: yamllint
            args: [-c, .yamllint.yaml]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/camunda/infraex-common-config
      rev: 1.3.6 # use tags until renovate supports sha: https://github.com/renovatebot/renovate/issues/22567
      hooks:
          - id: update-action-readmes-docker
