---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.0
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: ['-c', '.github/.yamllint']
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.1
  hooks:
  - id: actionlint
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
  - id: shellcheck
    args: ["--external-sources", "--source-path", ".github/workflows/scripts"]
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 37.414.1
  hooks:
  - id: renovate-config-validator
    args: ["--strict"]
