---
alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

server:
  persistentVolume:
    enabled: true
    size: 200Gi
  retention: 90d

serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: elasticsearch
      scrape_interval: 15s
      static_configs:
      - targets:
        - camunda-elasticsearch-metrics-hl.camunda-london.svc.cluster.local:9114
        - camunda-elasticsearch-metrics-hl.camunda-paris.svc.cluster.local:9114
        - camunda-elasticsearch-metrics-hl.camunda-frankfurt.svc.cluster.local:9114
    - job_name: zeebe
      scrape_interval: 15s
      metrics_path: /actuator/prometheus
      static_configs:
      - targets:
        - camunda-zeebe-0.camunda-zeebe.camunda-london.svc.cluster.local:9600
        - camunda-zeebe-0.camunda-zeebe.camunda-frankfurt.svc.cluster.local:9600
        - camunda-zeebe-0.camunda-zeebe.camunda-paris.svc.cluster.local:9600
        - camunda-zeebe-1.camunda-zeebe.camunda-london.svc.cluster.local:9600
        - camunda-zeebe-1.camunda-zeebe.camunda-frankfurt.svc.cluster.local:9600
        - camunda-zeebe-1.camunda-zeebe.camunda-paris.svc.cluster.local:9600
        - camunda-operate-hl.camunda-london.svc.cluster.local:8080
        - camunda-operate-hl.camunda-frankfurt.svc.cluster.local:8080
        - camunda-operate-hl.camunda-paris.svc.cluster.local:8080
        - camunda-zeebe-gateway-hl.camunda-london.svc.cluster.local:9600
        - camunda-zeebe-gateway-hl.camunda-frankfurt.svc.cluster.local:9600
        - camunda-zeebe-gateway-hl.camunda-paris.svc.cluster.local:9600
