---
zeebe:
    tolerations:
        - key: t-core-8-unstable
          operator: Exists
          effect: NoSchedule
        - key: t-core-16-unstable
          operator: Exists
          effect: NoSchedule
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: nodegroup
                            operator: In
                            values:
                                - t-core-8-unstable
                                - t-core-16-unstable
        podAntiAffinity: {}

operate:
    tolerations:
        - key: t-core-8-unstable
          operator: Exists
          effect: NoSchedule
        - key: t-core-16-unstable
          operator: Exists
          effect: NoSchedule
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: nodegroup
                            operator: In
                            values:
                                - t-core-8-unstable
                                - t-core-16-unstable
        podAntiAffinity: {}

tasklist:
    tolerations:
        - key: t-core-8-unstable
          operator: Exists
          effect: NoSchedule
        - key: t-core-16-unstable
          operator: Exists
          effect: NoSchedule
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: nodegroup
                            operator: In
                            values:
                                - t-core-8-unstable
                                - t-core-16-unstable
        podAntiAffinity: {}

identity:
    tolerations:
        - key: t-core-8-unstable
          operator: Exists
          effect: NoSchedule
        - key: t-core-16-unstable
          operator: Exists
          effect: NoSchedule
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: nodegroup
                            operator: In
                            values:
                                - t-core-8-unstable
                                - t-core-16-unstable
        podAntiAffinity: {}

connectors:
    tolerations:
        - key: t-core-8-unstable
          operator: Exists
          effect: NoSchedule
        - key: t-core-16-unstable
          operator: Exists
          effect: NoSchedule
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: nodegroup
                            operator: In
                            values:
                                - t-core-8-unstable
                                - t-core-16-unstable
        podAntiAffinity: {}

optimize:
    tolerations:
        - key: t-core-8-unstable
          operator: Exists
          effect: NoSchedule
        - key: t-core-16-unstable
          operator: Exists
          effect: NoSchedule
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: nodegroup
                            operator: In
                            values:
                                - t-core-8-unstable
                                - t-core-16-unstable
        podAntiAffinity: {}

zeebeGateway:
    tolerations:
        - key: t-core-8-unstable
          operator: Exists
          effect: NoSchedule
        - key: t-core-16-unstable
          operator: Exists
          effect: NoSchedule
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                          - key: nodegroup
                            operator: In
                            values:
                                - t-core-8-unstable
                                - t-core-16-unstable
        podAntiAffinity: {}

elasticsearch:
    master:
        tolerations:
            - key: t-core-8-unstable
              operator: Exists
              effect: NoSchedule
            - key: t-core-16-unstable
              operator: Exists
              effect: NoSchedule
        affinity:
            nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                        - matchExpressions:
                              - key: nodegroup
                                operator: In
                                values:
                                    - t-core-8-unstable
                                    - t-core-16-unstable
            podAntiAffinity: {}
