---
name: Lint

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: asdf-vm/actions/setup@v3
    - name: Install tooling required for pre-commit
      run: |
        for tool in actionlint shellcheck terraform tflint ; do
          asdf plugin add "${tool}"
          asdf install "${tool}"
        done
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --verbose
