---
name: lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@3b329de512b6e0d86345426754f63abc6c258066 # 1.2.16
        secrets: inherit
