---
name: Lint

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
            - uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
            - name: Install tooling required for pre-commit
              run: |
                  for tool in actionlint shellcheck terraform tflint ; do
                    asdf plugin add "${tool}"
                    asdf install "${tool}"
                  done
            - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
              with:
                  extra_args: --all-files --verbose
