---
name: Teleport Migration Procedure (Snapshot)

on:
    schedule:
        - cron: 0 3 * * 1-5   # At 03:00 on every day-of-week from Monday through Friday.
    pull_request:
        # in current form is very limited to 8.7 to 8.8 migration only
        branches-ignore:
            - stable/**
        paths:
            - .github/workflows/migration_procedure_snapshot.yml
            - .github/workflows/reuseable_aws_operational_procedure.yml
            - aws/dual-region/kubernetes/**/**.yml
            - aws/dual-region/scripts/generate_zeebe_helm_values.sh
    workflow_dispatch:
        inputs:
            previous-helm-chart:
                description: Release Helm chart version
            migration-helm-chart:
                description: Helm chart version for migration
            keep-alive:
                description: Keep the clusters alive after the procedure (default false)
                type: boolean
            skip-failover:
                description: Skip the failover part of the procedure (default false)
                type: boolean
            skip-failback:
                description: Skip the failback part of the procedure (default false)
                type: boolean

env:
    IS_SCHEDULE: ${{ contains(github.head_ref, 'schedules/') || github.event_name == 'schedule' && 'true' || 'false' }}

    # renovate: datasource=helm depName=camunda-platform registryUrl=https://helm.camunda.io versioning=regex:^12(\.(?<minor>\d+))?(\.(?<patch>\d+))?$
    PREVIOUS_HELM_CHART: 12.6.1
    MIGRATION_HELM_CHART: SNAPSHOT

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:

    # Workaround as reuseable workflows do not support env vars from calling workflow yet
    convert_env_to_output:
        name: Convert env to output
        runs-on: ubuntu-latest
        outputs:
            PREVIOUS_HELM_CHART: ${{ steps.set-outputs.outputs.PREVIOUS_HELM_CHART }}
            MIGRATION_HELM_CHART: ${{ steps.set-outputs.outputs.MIGRATION_HELM_CHART }}
        steps:
            - name: Set outputs
              id: set-outputs
              run: |
                  {
                    echo "PREVIOUS_HELM_CHART=${{ inputs.previous-helm-chart || env.PREVIOUS_HELM_CHART }}"
                    echo "MIGRATION_HELM_CHART=${{ inputs.migration-helm-chart || env.MIGRATION_HELM_CHART }}"
                  } >> "$GITHUB_OUTPUT"

    deploy_previous_release:
        name: Deploy previous release only
        needs:
            - convert_env_to_output
        uses: ./.github/workflows/reusable_teleport_operational_procedure.yml
        with:
            helmChartVersion: ${{ needs.convert_env_to_output.outputs.PREVIOUS_HELM_CHART }}
            deployOnly: true
            overwriteBranch: stable/8.7
        secrets: inherit

    deploy_migration_release:
        name: Deploy snapshot with migration enabled
        needs:
            - deploy_previous_release
            - convert_env_to_output
        uses: ./.github/workflows/reusable_teleport_operational_procedure.yml
        with:
            helmChartVersion: ${{ needs.convert_env_to_output.outputs.MIGRATION_HELM_CHART }}
            migrationEnabled: true
            cluster_0_namespace: ${{ needs.deploy_previous_release.outputs.CLUSTER_0_NAMESPACE }}
            cluster_1_namespace: ${{ needs.deploy_previous_release.outputs.CLUSTER_1_NAMESPACE }}
            backup_name: ${{ needs.deploy_previous_release.outputs.BACKUP_NAME }}
            keepAlive: ${{ github.event.inputs.keep-alive || false }}
            skipFailover: ${{ github.event.inputs.skip-failover || false }}
            skipFailback: ${{ github.event.inputs.skip-failback || false }}
        secrets: inherit

    report-failure:
        name: Report failures
        if: failure()
        runs-on: ubuntu-latest
        needs:
            - deploy_migration_release
        steps:
            - name: Notify in Slack in case of failure
              id: slack-notification
              if: env.IS_SCHEDULE == 'true'
              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@eb9d51b4dc89deeda7fc160166f378725ee0f06a # 1.5.3
              with:
                  vault_addr: ${{ secrets.VAULT_ADDR }}
                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
