name: Nightly AWS Region Cleanup

on:
  schedule:
  - cron: '0 5 * * 1-5'
  workflow_dispatch:

env:
  AWS_PROFILE: infex

jobs:
  aws-nightly-cleanup:
    runs-on: ubuntu-latest
    # Other dependencies from hosted runner
    # AWS CLI
    # indirectly node used by actions

    steps:
    - uses: actions/checkout@v4
    
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false
        secrets: |
          secret/data/products/infrastructure-experience/ci/common AWS_ACCESS_KEY;
          secret/data/products/infrastructure-experience/ci/common AWS_SECRET_KEY;

    # Official action does not support profiles
    - name: Add profile credentials to ~/.aws/credentials 
      run: |
          aws configure set aws_access_key_id ${{ steps.secrets.outputs.AWS_ACCESS_KEY }} --profile ${{ env.AWS_PROFILE }}
          aws configure set aws_secret_access_key ${{ steps.secrets.outputs.AWS_SECRET_KEY }} --profile ${{ env.AWS_PROFILE }}
          aws configure set region eu-west-2 --profile ${{ env.AWS_PROFILE }}

    - name: Install Cloud Nuke
      run: |
        wget https://github.com/gruntwork-io/cloud-nuke/releases/download/v0.33.0/cloud-nuke_linux_amd64
        chmod +x cloud-nuke_linux_amd64
    
    # This is likely to fail, therefore we ignore the error
    # We're ignoring ec2_dhcp_option as they couldn't be deleted
    # cloudtrail is managed by IT and can't be deleted either
    - name: Run Cloud Nuke
      timeout-minutes: 45
      env:
        DISABLE_TELEMETRY: "true"
      run: |
        ./cloud-nuke_linux_amd64 aws --region eu-west-2 --region eu-west-3 --force --newer-than 4h --exclude-resource-type ec2_dhcp_option --exclude-resource-type cloudtrail || true
    
    # Following will delete global resources and things that cloud-nuke does not support
    - name: Delete additional AWS resources
      timeout-minutes: 15
      run: |
        echo "Deleting additional resources..."
        # mac is using BSD xargs, where -n 1 and -I {} are required to make it work
        # in GNU xargs -n 1 and -I are mutually exclusive
        # KMS keys can't be deleted due to resource policies, requires manual intervention

        echo "Deleting IAM Roles"
        # Detach permissions and profile instances and delete IAM roles
        role_arns=$(aws iam list-roles --query 'Roles[?contains(RoleName, `nightly`)].RoleName' --output text)

        read -r -a role_arns_array <<< "$role_arns"

        for role_arn in "${role_arns_array[@]}"
        do
            echo "Removing instance profiles and policies of role: $role_arn"
            attached_policy_arns=$(aws iam list-attached-role-policies --role-name "$role_arn" --query 'AttachedPolicies[].PolicyArn' --output text)
            read -r -a attached_policy_arns_array <<< "$attached_policy_arns"

            for policy_arn in "${attached_policy_arns_array[@]}"
            do
                echo "Removing attached policy: $policy_arn"
                aws iam detach-role-policy --role-name "$role_arn" --policy-arn "$policy_arn"
            done

            policy_arns=$(aws iam list-role-policies --role-name "$role_arn" --query 'PolicyNames' --output text)
            read -r -a policy_arns_array <<< "$policy_arns"

            for policy_arn in "${policy_arns_array[@]}"
            do
                echo "Deleting policy: $policy_arn"
                aws iam delete-role-policy --role-name "$role_arn" --policy-name "$policy_arn"
            done

            instance_profile_arns=$(aws iam list-instance-profiles-for-role --role-name "$role_arn" --query 'InstanceProfiles[].InstanceProfileName' --output text)
            read -r -a instance_profile_arns_array <<< "$instance_profile_arns"

            for instance_profile_arn in "${instance_profile_arns_array[@]}"
            do
                echo "Removing instance profile: $instance_profile_arn"
                aws iam remove-role-from-instance-profile --instance-profile-name "$instance_profile_arn" --role-name "$role_arn"
            done

            echo "Deleting role: $role_arn"
            aws iam delete-role --role-name "$role_arn"

        done

        echo "Deleting IAM Policies"
        # Delete Policies
        iam_policies=$(aws iam list-policies --query 'Policies[?contains(PolicyName, `nightly`)].Arn' --output text)

        read -r -a iam_policies_array <<< "$iam_policies"

        for iam_policy in "${iam_policies_array[@]}"
        do
            echo "Deleting policy: $iam_policy"
            aws iam delete-policy --policy-arn "$iam_policy"
        done

        echo "Deleting OIDC Providers"
        # Delete OIDC Provider
        oidc_providers=$(aws iam list-open-id-connect-providers --query 'OpenIDConnectProviderList[?contains(Arn, `eu-west-2`) || contains(Arn, `eu-west-3`)].Arn' --output text)

        read -r -a oidc_providers_array <<< "$oidc_providers"

        for oidc_provider in "${oidc_providers_array[@]}"
        do
            echo "Deleting OIDC Provider: $oidc_provider"
            aws iam delete-open-id-connect-provider --open-id-connect-provider-arn "$oidc_provider"
        done

        echo "Deleting VPC Peering Connections"
        # Delete VPC Peering Connection
        peering_connection_ids=$(aws ec2 describe-vpc-peering-connections --region eu-west-2 --query 'VpcPeeringConnections[?Status.Code == `active` && Tags[?contains(Value, `nightly`)]]'.VpcPeeringConnectionId --output text)

        read -r -a peering_connection_ids_array <<< "$peering_connection_ids"

        for peering_connection_id in "${peering_connection_ids_array[@]}"
        do
            echo "Deleting VPC Peering Connection: $peering_connection_id"
            aws ec2 delete-vpc-peering-connection --region eu-west-2 --vpc-peering-connection-id "$peering_connection_id"
        done

    # The second run should remove the remaining resources (VPCs) and fail if there's anything left
    - name: Run Cloud Nuke
      timeout-minutes: 45
      env:
        DISABLE_TELEMETRY: "true"
      run: |
        ./cloud-nuke_linux_amd64 aws --region eu-west-2 --region eu-west-3 --force --newer-than 4h --exclude-resource-type ec2_dhcp_option --exclude-resource-type cloudtrail
