---
name: Nightly AWS EKS Operational Procedure Test

on:
  schedule:
  - cron: '0 2 * * 1-5'
  workflow_dispatch:

env:
  AWS_PROFILE: infex

jobs:
  aws-eks-2-operational-procedure-test:
    runs-on: ubuntu-latest
    # Other dependencies from hosted runner
    # AWS CLI
    # indirectly node used by actions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get go.mod details
      uses: Eun/go-mod-details@v1
      id: go-mod-details
      with:
        modfile: ${{ github.workspace }}/test/go.mod

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.go-mod-details.outputs.go_version }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.3"

    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false
        secrets: |
          secret/data/products/infrastructure-experience/ci/common AWS_ACCESS_KEY;
          secret/data/products/infrastructure-experience/ci/common AWS_SECRET_KEY;

    # Official action does not support profiles
    - name: Add profile credentials to ~/.aws/credentials
      run: |
          aws configure set aws_access_key_id ${{ steps.secrets.outputs.AWS_ACCESS_KEY }} --profile ${{ env.AWS_PROFILE }}
          aws configure set aws_secret_access_key ${{ steps.secrets.outputs.AWS_SECRET_KEY }} --profile ${{ env.AWS_PROFILE }}
          aws configure set region eu-west-2 --profile ${{ env.AWS_PROFILE }}

    - name: Generate random cluster_name and bucket_name
      id: random
      run: |
        echo "CLUSTER_NAME=nightly-$(head /dev/urandom | tr -dc 'a-z0-9' | head -c 8)" >> "$GITHUB_ENV"
        echo "BUCKET_NAME=nightly-$(head /dev/urandom | tr -dc 'a-z0-9' | head -c 8)" >> "$GITHUB_ENV"

    - name: Terratest Terraform Init And Apply
      working-directory: ./test
      timeout-minutes: 46
      run: |
        go test --count=1 -v -timeout 45m ./multi_region_aws_operational_procedure_test.go -run TestSetupTerraform

    - name: Operational Procedure Test in 2 Regions - C8.3
      working-directory: ./test
      timeout-minutes: 46
      env:
        HELM_CHART_VERSION: "8.3.11"
        BACKUP_NAME: nightly-8.3
      run: |
        go test --count=1 -v -timeout 45m ./multi_region_aws_operational_procedure_test.go -run TestAWSOperationalProcedure

    - name: Operational Procedure Test in 2 Regions - C8.4
      working-directory: ./test
      timeout-minutes: 46
      env:
        HELM_CHART_VERSION: "9.3.3"
        BACKUP_NAME: nightly-9.3
      run: |
        go test --count=1 -v -timeout 45m ./multi_region_aws_operational_procedure_test.go -run TestAWSOperationalProcedure

    - name: Operational Procedure Test in 2 Regions - C8.5
      working-directory: ./test
      timeout-minutes: 46
      env:
        HELM_CHART_VERSION: "10.0.0"
        BACKUP_NAME: nightly-8.5
      run: |
        go test --count=1 -v -timeout 45m ./multi_region_aws_operational_procedure_test.go -run TestAWSOperationalProcedure

    - name: Operational Procedure Test in 2 Regions - SNAPSHOT
      working-directory: ./test
      timeout-minutes: 46
      env:
        HELM_CHART_VERSION: "10.0.0"
        BACKUP_NAME: nightly-SNAPSHOT
        GLOBAL_IMAGE_TAG: SNAPSHOT
      run: |
        go test --count=1 -v -timeout 45m ./multi_region_aws_operational_procedure_test.go -run TestAWSOperationalProcedure

    - name: Terratest Terraform Teardown
      if: always()
      working-directory: ./test
      timeout-minutes: 31
      run: |
        go test --count=1 -v -timeout 30m ./multi_region_aws_operational_procedure_test.go -run TestTeardownTerraform

    - name: Remove profile credentials from ~/.aws/credentials
      if: always()
      run: |
        rm -rf ~/.aws/credentials
