---
name: Test Reusable Workflow on Push

on:
    push:
        branches:
            - reusable-gh-workflow

jobs:
    test-reusable:
        uses: ./.github/workflows/reusable_teleport_operational_procedure.yml
        with:
            helmChartVersion: 0.0.0-snapshot-alpha
            helmChartName: oci://ghcr.io/camunda/helm/camunda-platform
            globalImageTag: SNAPSHOT
            awsProfile: infex
            testsTfBinaryName: terraform
            namespacePrefix: infraex-
            clusterName: camunda-ci-eks
            labels: janitor/ttl=1h camunda.cloud/ephemeral=true
            cluster: camunda.teleport.sh-camunda-ci-eks
            backupBucket: tests-c8-multi-region-es-eu-central-1
            helmReleaseName: camunda
            zeebeClusterSize: 8
        secrets:
            VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
            VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
            VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
